yii-examples/controllers/DocumentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Comment;
use app\models\Document;
use app\models\DocumentSearch;
use app\models\Notification;
use lib\web\Controller;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * DocumentController implements the CRUD actions for Document model.
 */
class DocumentController extends Controller
{
    public $enableCsrfValidation = false;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => [
                            'signature', 'xml',
                        ],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['documents', 'document.upload'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => [
                            'approve-document'
                        ],
                        'roles'   => [
                            'document.approve'
                        ],
                    ],
                    [
                        'allow'   => true,
                        'actions' => [
                            'delete'
                        ],
                        'roles'   => [
                            'document.delete'
                        ],
                    ],
                ]
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionDownload($id, $version = null)
    {
        $doc = $this->findModel($id, $version);
        if (!$doc) {
            throw new NotFoundHttpException();
        }

        return Yii::$app->response->sendFile($doc->getFilePath(), $doc->name);
    }

    /**
     * Lists all Document models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel  = new DocumentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                'searchModel'  => $searchModel,
                'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Document model.
     * @param  integer $id
     * @return mixed
     */
    public function actionView($id, $version = null)
    {
        $doc = $this->findModel($id, $version);

        return $this->render('view', [
                'model'           => $doc,
                'documentModel'   => new Document([
                    'id'         => $doc->id,
                    'project_id' => $doc->project_id,
                    'title'      => $doc->title,
                    'version'    => $doc->version + 1,
                    ]),
                'commentList'     => new ActiveDataProvider([
                    'query'      => $doc->getComments(),
                    'pagination' => [
                        'pageSize' => 20,
                    ],
                    ]),
                'newComment'      => new Comment([
                    'document_id' => $doc->id,
                    'project_id'  => $doc->project_id,
                    'doc_version' => $doc->version,
                    ]),
                'previousVerions' => new ActiveDataProvider([
                    'query'      => Document::find()->orderBy('version DESC')->where(['id' => $id]),
                    'pagination' => [
                        'pageSize' => 20,
                    ],
                    ]),
        ]);
    }

    /**
     * Creates a new Document model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Document();

        if ($model->load(Yii::$app->request->post()) && $model->save() && $model->file->saveAs($model->getFilePath())) {
            $url          = [
                'project/view',
                'id'   => $model->project_id,
                'type' => $model->type,
            ];
            $notification = new Notification('notice');
            $notification->add(Notification::NOTIFICATION_EXTERNAL, [
                'title'   => Yii::t('app/notification', 'NEW_DOCUMENT_NOTIFICATION_TITLE'),
                'content' => Yii::t('app/notification', 'NEW_DOCUMENT_NOTIFICATION_CONTENT', Url::to($url, true)),
                ], [
                'permission' => 'projects',
                'unit'       => [$model->project->owner_id, $model->project->company_id],
            ]);

            return $this->redirect($url);
        } else {
            return $this->render('create', [
                    'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Document model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param  integer $id
     * @return mixed
     */
    public function actionUpdate($id, $version)
    {
        $model = $this->findModel($id, $version);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id, 'version' => $model->version]);
        } else {
            return $this->render('update', [
                    'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Document model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param  integer $id
     * @return mixed
     */
    public function actionDelete($id, $version)
    {
        $this->findModel($id, $version)->delete();

        return $this->redirect(['index']);
    }

    public function actionApproveDocument($id, $version)
    {
        $model = $this->findModel($id, $version);

        if ($model->isApprovedByType($model->type)) {
            Yii::$app->session->setFlash('danger', Yii::t('app/document', 'DOCUMENT_APPROVED'));

            return $this->redirect(['project/view', 'id' => $model->project_id, 'type' => $model->type]);
        }

        $url = ['project/view', 'id' => $model->project_id, 'type' => $model->type];
        if ($model->approve(Yii::$app->user->identity)) {
            $notification = new Notification('notice');
            $notification->add(Notification::NOTIFICATION_EXTERNAL, [
                'title'   => Yii::t('app/notification', 'DOCUMENT_APPROVED_NOTIFICATION_TITLE'),
                'content' => Yii::t('app/notification', 'DOCUMENT_APPROVED_NOTIFICATION_CONTENT', Url::to($url, true)),
                ], [
                'permission' => 'projects',
                'unit'       => [$model->project->owner_id, $model->project->company_id],
            ]);

            Yii::$app->session->setFlash('success', Yii::t('app/document', 'DOCUEMENT_HAS_BEEN_APPROVED'));
        } else {
            Yii::$app->session->setFlash('danger', Yii::t('app/document', 'DOCUMENT_CANNOT_BE_APPROVED'));
        }

        return $this->redirect($url);
    }

    /**
     * Finds the Document model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param  integer               $id
     * @return Document              the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $version = null)
    {
        if ($version === null) {
            $version = Document::find()->select([new Expression('MAX(version) AS mv')])->where(['id' => $id])->scalar();
        }
        if ($version !== false && ($model = Document::findOne(['id' => $id, 'version' => $version])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionXml($id)
    {
        Yii::$app->response->format = Response::FORMAT_XML;

        return $this->findModel($id);
    }

    public function actionTask($id)
    {
        Yii::$app->response->format = Response::FORMAT_XML;

        Yii::$app->response->formatters[Response::FORMAT_XML]['rootTag'] = 'TaskList';

        return $this->findModel($id)->getCryptoTask();
    }

    public function actionSignature($id)
    {
        Yii::$app->response->format = Response::FORMAT_XML;

        $model = $this->findModel($id);

        $model->signature = Yii::$app->request->post('signature');

        if (!$model->signature) {
            Yii::$app->response->formatters[Response::FORMAT_XML]['rootTag'] = 'error';
            throw new BadRequestHttpException();
        }

        $model->signature_type = Document::SIGNED_DIGITALLY;
        if (!$model->save()) {
            Yii::$app->response->formatters[Response::FORMAT_XML]['rootTag'] = 'error';

            return $model->errors;
        }

        Yii::$app->response->format = Response::FORMAT_RAW;

        return 'OK';
    }

}

yii-examples/views/project/_form.php
<?php
use app\models\Unit;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\User $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="project-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => 64]) ?>

    <?php if (Yii::$app->user->can('project.admin')): ?>
        <?= $form->field($model, 'owner_id')->dropDownList(ArrayHelper::map(Unit::getResearchUnits(), 'id', 'name')) ?>
    <?php endif; ?>

    <?php if (!Yii::$app->user->can('project.view.company')): ?>
        <?= $form->field($model, 'company_id')->dropDownList(ArrayHelper::map(Unit::getCompanies(), 'id', 'name'), ['prompt' => '']) ?>
    <?php endif; ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'CREATE'), ['class' => 'btn btn-success']) ?>
        <?= Html::a(Yii::t('app', 'CANCEL'), ['index'], ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii-examples/views/project/append-members.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\ModelSearch $searchModel
 */
$this->title = Yii::t('app/project', 'ASSIGN_PROJECT_MEMBERS', $model->name);
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel'  => $searchModel,
        'layout'       => '{items}{pager}',
        'columns'      => [
            ['class' => 'yii\grid\CheckBoxColumn'],
            'name',
            'last_name',
            'username',
            'email:email'
        ],
    ]);
    ?>
</div>

yii-examples/views/project/archive.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjectApprovalSettingSearchRules */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app/project', 'ARCHIVE');
?>
<div class="project-approval-rules-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'columns'      => [
            'name',
            ['class'          => 'yii\grid\ActionColumn',
                'contentOptions' => [
                    'class' => 'action-icon-tab',
                ],
                'template'       => '{download}',
                'buttons'        => [
                    'download' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-download icon-tab icon-middle"></span>', $url, [
                            'title'     => Yii::t('app', 'DOWNLOAD'),
                            'data-pjax' => '0',
                    ]);
                },
                ]
            ]
        ],
    ]);
    ?>
</div>

yii-examples/views/project/create.php
<?php
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\User $model
 */
$this->title = Yii::t('app/project', 'CREATE_PROJECT', []);
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>

yii-examples/views/project/edi.php
<?php
use app\models\Document;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjectApprovalSettingSearchRules */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app/project', 'PROJECTS');
?>
<div class="project-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php if (Yii::$app->user->can('project.create')): ?>
        <p>
            <?= Html::a(Yii::t('app/project', 'CREATE_PROJECT', []), ['create'], ['class' => 'btn btn-success']) ?>
        </p>
    <?php endif; ?>
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'columns'      => [
            'name',
            ['class'          => 'yii\grid\ActionColumn',
                'contentOptions' => [
                    'class' => 'action-icon-tab',
                ],
                'template'       => '{get-info}',
                'buttons'        => [
                    'get-info' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open icon-tab icon-middle"></span>', $url . '&type=' . Document::PROJECT_DOCUMENT, [
                            'title'     => Yii::t('yii', 'View'),
                            'data-pjax' => '0',
                    ]);
                }
                ]
            ]
        ],
    ]);
    ?>
</div>

yii-examples/views/project/index.php
<?php
use app\models\Document;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjectApprovalSettingSearchRules */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app/project', 'PROJECTS');
?>
<div class="project-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php if (Yii::$app->user->can('project.create')): ?>
        <p>
            <?= Html::a(Yii::t('app/project', 'CREATE_PROJECT', []), ['create'], ['class' => 'btn btn-success']) ?>
        </p>
    <?php endif; ?>
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'columns'      => [
            'name',
            [
                'header'        => Yii::t('app/unit', 'COMPANY'),
                'format'        => 'html',
                'enableSorting' => true,
                'value'         => function ($model) {
                if ($company = $model->getCompany()) {
                    return $company->name;
                } else {
                    return '';
                }
            }
            ],
            [
                'header'        => Yii::t('app/project', 'EXTERNAL_DATA'),
                'format'        => 'html',
                'enableSorting' => true,
                'value'         => function ($model) {
                return Html::a('www', '/external-data?ExternalDataSearch[project_id]=' . $model->id, []);
            }
            ],
            ['class'          => 'yii\grid\ActionColumn',
                'contentOptions' => [
                    'class' => 'action-icon-tab',
                ],
                'template'       => '{view}{update}{member-list}{process}{add-to-archive}{delete}',
                'buttons'        => [
                    'view' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open icon-tab icon-middle"></span>', $url . '&type=' . Document::PROJECT_DOCUMENT, [
                            'title'     => Yii::t('yii', 'View'),
                            'data-pjax' => '0',
                    ]);
                },
                    'update'         => function ($url, $model) {
                    if (!Yii::$app->user->can('project.update')) {
                        return false;
                    }

                    return Html::a('<span class="glyphicon glyphicon-pencil icon-tab icon-middle"></span>', $url, [
                            'title'     => Yii::t('yii', 'Update'),
                            'data-pjax' => '0',
                    ]);
                },
                    'process' => function ($url, $model) {
                    if (!Yii::$app->user->can('project.process.view')) {
                        return false;
                    }

                    return Html::a('<span class="glyphicon glyphicon-map-marker icon-middle"></span>', $url, [
                            'title' => Yii::t('app/project', 'SET_PROCESS'),
                    ]);
                },
                    'add-to-archive' => function ($url, $model) {
                    if (!Yii::$app->user->can('project.archive.add')) {
                        return false;
                    }

                    if (!$model->isLocked()) {
                        return false;
                    }

                    return Html::a('<span class="glyphicon glyphicon-cloud icon-middle"></span>', $url, [
                            'title'        => Yii::t('app/project', 'ADD_TO_ARCHIVE'),
                            'data-confirm' => Yii::t('app', 'ARCHIVE_CONFIRMATION'),
                    ]);
                },
                    'delete' => function ($url, $model) {
                    if (!Yii::$app->user->can('project.delete')) {
                        return false;
                    }

                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                            'title'        => Yii::t('yii', 'Delete'),
                            'data-confirm' => Yii::t('app', 'DELETE_CONFIRMATION_MESSAGE'),
                            'data-method'  => 'post',
                            'data-pjax'    => '0',
                    ]);
                },
                ]
            ]
        ],
    ]);
    ?>
</div>

yii-examples/views/project/member-list.php
<?php
use app\models\User;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\ModelSearch $searchModel
 */
$this->title = Yii::t('app/project', 'CHOOSE_PROJECT_MEMBERS');
?>
<div class="user-index">
    <?php $form        = ActiveForm::begin(); ?>

    <?= $form->field($model, 'member_id')->dropDownList(ArrayHelper::map(User::getActive(), 'id', 'fullName'), ['multiple' => true]) ?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'CREATE') : Yii::t('app', 'UPDATE'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'CANCEL'), ['index'], ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

yii-examples/views/project/update.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ProjectApprovalRules */

$this->title = Yii::t('app/project', 'UPDATE_PROJECT', [
        'modelClass' => 'Project Approval Rules',
    ]) . ': ' . $model->name;
?>
<div class="project-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>

yii-examples/views/project/view.php
<?php
use app\models\Document;
use yii\bootstrap\Modal;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Project */
?>
<div class="project-view">

    <h1><?= Html::encode($model->name) ?></h1>

    <p>
        <?php if (Yii::$app->user->can('project.update')): ?>
            <?= Html::a(Yii::t('app', 'EDIT'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php endif; ?>
        <?php if (Yii::$app->user->can('project.delete')): ?>
            <?=
            Html::a(Yii::t('app', 'DELETE'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data'  => [
                    'confirm' => Yii::t('app', 'DELETE_CONFIRMATION_MESSAGE'),
                    'method'  => 'post',
                ],
            ])
            ?>
        <?php endif; ?>
        <?= Html::a(Yii::t('app', 'BACK'), ['index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app/project', 'GET_XML'), ['get-info', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
        <?= Html::a(Yii::t('app/project', 'GET_EDI'), ['get-edi', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
    </p>

    <?=
    DetailView::widget([
        'model'      => $model,
        'attributes' => [
            'name',
            [
                'label' => Yii::t('app/project', 'COMPANY_APPROVER'),
                'name'  => 'company_approver_id',
                'value' => $model->getCompany() ? $model->getCompany()->name : null,
            ],
            [
                'label' => Yii::t('app/project', 'INSTITUTION_APPROVER'),
                'name'  => 'institution_approver_id',
                'value' => $model->getOwner() ? $model->getOwner()->name : null,
            ],
            [
                'label' => Yii::t('app/project', 'LOCK_DATE'),
                'name'  => 'lock_date',
                'value' => $model->toInfo()['lock_date'],
            ],
        ],
    ])
    ?>
</div>
<div class="document-index">
    <?= Html::tag('div', '', ['id' => 'appletContainer']); ?>
    <?php $this->registerJs('
    jQuery("#loadButton").click(function () {
        if (typeof signer !== "object") {
            jQuery("#appletContainer").load("' . Url::to(['applet'], true) . '",{},function () {
                jQuery("#loadButton").remove();
                signer.initialize();
            });
        }
    });'); ?>
    <h1><?= Html::encode(Yii::t('app/project', 'DOCUMENT_LIST')) ?></h1>
    <?php if ($documentModel->canBeUploadedIntoProject()): ?>
        <?php
        Modal::begin([
            'id'           => 'modal',
            'toggleButton' => [
                'class' => 'btn btn-success modalButton',
                'label' => Yii::t('app/document', 'UPLOAD_PROJECT_DOCUMENT'),
            ],
        ]);
        ?>
        <div class='modalContent'>
            <?=
            $this->render('/document/_form', [
                'model' => $documentModel,
                'type'  => $type,
            ])
            ?>
        </div>
        <?php Modal::end(); ?>
    <?php endif; ?>

    <?php if ($documentModel->canBeUploadedIntoInspection()): ?>
        <?php
        Modal::begin([
            'id'           => 'modal',
            'toggleButton' => [
                'class' => 'btn btn-success modalButton',
                'label' => Yii::t('app/document', 'UPLOAD_INSPECTION_DOCUMENT'),
            ],
        ]);
        ?>
        <div class='modalContent'>
            <?=
            $this->render('/document/_form', [
                'model' => $documentModel,
                'type'  => $type,
            ])
            ?>
        </div>
        <?php Modal::end(); ?>
    <?php endif; ?>
    <?php if ($type == Document::INSPECTION_DOCUMENT): ?>
        <?=
        GridView::widget([
            'dataProvider' => $documentList,
            'columns'      => [
                ['class' => 'yii\grid\SerialColumn'],
                'title',
                'version',
                'created_at',
                [
                    'header'        => Yii::t('app/document', 'IS_APPROVED_BY_INSTITUTION'),
                    'format'        => 'html',
                    'enableSorting' => true,
                    'value'         => function ($model) {
                    return $model->getInstitutionApprover() ? Yii::t('app', 'YES') : Yii::t('app', 'NO');
                }
                ],
                [
                    'header'        => Yii::t('app/document', 'IS_SIGNED'),
                    'format'        => 'html',
                    'enableSorting' => true,
                    'value'         => function ($model) {
                    return Yii::t('app/document', $model->getSignatureType());
                }
                ],
                [
                    'header' => Yii::t('app', "SIGNATURE") . '<br />' . Html::button(Yii::t('app', 'LOAD_APPLET'), ['class' => 'btn btn-primary', 'id' => 'loadButton']),
                    'format' => 'raw',
                    'value'  => function ($model) {
                    if ($model->signature) {
                        return '<span class="glyphicon glyphicon-ok"></span>';
                    } else {
                        return Html::a('<span class="glyphicon glyphicon-barcode"></span>', '#', [
                                'title' => Yii::t('app', 'SIGN'),
                                'class' => 'signButton',
                                'style' => 'display: none;',
                                'data'  => [
                                    'task' => Url::to(['document/task', 'id' => $model->id], true),
                                ],
                        ]);
                    }
                }
                ],
                [
                    'class'      => 'yii\grid\ActionColumn',
                    'template'   => '{view}{update}{approve-document}',
                    'urlCreator' => function ($action, $model, $key, $index) {
                    $params    = is_array($key) ? $key : ['id' => (string) $key];
                    $params[0] = 'document/' . $action;

                    return Url::toRoute($params);
                },
                    'buttons' => [
                        'approve-document' => function ($url, $model) {
                        if ($model->isApprovedByType($model->type) || !Document::canApproveType($model->type)) {
                            return false;
                        }

                        return Html::a('<span class="glyphicon glyphicon-hand-up icon-tab icon-middle"></span>', $url, [
                                'title'     => Yii::t('app/document', 'APPROVE_DOCUMENT'),
                                'data-pjax' => '0',
                        ]);
                    },
                        'update' => function ($url, $model) {
                        if ($model->isApprovedByType($model->type) || !Document::canManageType($model->type)) {
                            return false;
                        }

                        return Html::a('<span class="glyphicon glyphicon-pencil icon-tab icon-middle"></span>', $url, [
                                'title'     => Yii::t('yii', 'Update'),
                                'data-pjax' => '0',
                        ]);
                    },
                        'delete' => function ($url, $model) {
                        if ($model->isApprovedByType($model->type) || !Document::canManageType($model->type)) {
                            return false;
                        }

                        return Html::a('<span class="glyphicon glyphicon-trash icon-tab icon-middle"></span>', $url, [
                                'title'     => Yii::t('yii', 'Delete'),
                                'data-pjax' => '0',
                        ]);
                    },
                    ]
                ],
            ]
        ]);
        ?>
    <?php elseif ($type == Document::PROJECT_DOCUMENT): ?>
        <?=
        GridView::widget([
            'dataProvider' => $documentList,
            'columns'      => [
                ['class' => 'yii\grid\SerialColumn'],
                'title',
                'version',
                'created_at',
                [
                    'header'        => Yii::t('app/document', 'IS_APPROVED_BY_COMPANY'),
                    'format'        => 'html',
                    'enableSorting' => true,
                    'value'         => function ($model) {
                    return $model->getCompanyApprover() ? Yii::t('app', 'YES') : Yii::t('app', 'NO');
                }
                ],
                [
                    'header'        => Yii::t('app/document', 'IS_SIGNED'),
                    'format'        => 'html',
                    'enableSorting' => true,
                    'value'         => function ($model) {
                    return Yii::t('app/document', $model->getSignatureType());
                }
                ],
                [
                    'header' => Yii::t('app', "SIGNATURE") . '<br />' . Html::button(Yii::t('app', 'LOAD_APPLET'), ['class' => 'btn btn-primary', 'id' => 'loadButton']),
                    'format' => 'raw',
                    'value'  => function ($model) {
                    if ($model->signature) {
                        return '<span class="glyphicon glyphicon-ok"></span>';
                    } else {
                        return Html::a('<span class="glyphicon glyphicon-barcode"></span>', '#', [
                                'title' => Yii::t('app', 'SIGN'),
                                'class' => 'signButton',
                                'style' => 'display: none;',
                                'data'  => [
                                    'task' => Url::to(['document/task', 'id' => $model->id], true),
                                ],
                        ]);
                    }
                }
                ],
                [
                    'class'      => 'yii\grid\ActionColumn',
                    'template'   => '{view}{approve-document}',
                    'urlCreator' => function ($action, $model, $key, $index) {
                    $params    = is_array($key) ? $key : ['id' => (string) $key];
                    $params[0] = 'document/' . $action;

                    return Url::toRoute($params);
                },
                    'buttons' => [
                        'approve-document' => function ($url, $model) {
                        if ($model->isApprovedByType($model->type) || !Document::canApproveType($model->type)) {
                            return false;
                        }

                        return Html::a('<span class="glyphicon glyphicon-hand-up icon-tab icon-middle"></span>', $url, [
                                'title'     => Yii::t('app/document', 'APPROVE_DOCUMENT'),
                                'data-pjax' => '0',
                        ]);
                    },
                        'delete' => function ($url, $model) {
                        if ($model->isApprovedByType($model->type) || !Document::canManageType($model->type)) {
                            return false;
                        }

                        return Html::a('<span class="glyphicon glyphicon-trash icon-tab icon-middle"></span>', $url, [
                                'title'     => Yii::t('yii', 'Delete'),
                                'data-pjax' => '0',
                        ]);
                    },
                    ]
                ],
            ]
        ]);
        ?>
    <?php endif; ?>
</div>