yii-examples/controllers/CommentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Comment;
use app\models\CommentSearch;
use app\models\Notification;
use lib\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * CommentController implements the CRUD actions for Comment model.
 */
class CommentController extends Controller
{
    public $enableCsrfValidation = false;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => [
                            'signature', 'xml',
                        ],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Comment models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel  = new CommentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                'searchModel'  => $searchModel,
                'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Comment model.
     * @param  integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
                'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Comment model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Comment();

        if ($model->load(Yii::$app->request->post()) && ($model->author_id = Yii::$app->user->id) && $model->save()) {
            $url          = ['document/view',
                'id'      => $model->document_id,
                'version' => $model->doc_version,
            ];
            $notification = new Notification('notice');
            $notification->add(Notification::NOTIFICATION_EXTERNAL, [
                'title'   => Yii::t('app/notification', 'NEW_COMMENT_NOTIFICATION_TITLE'),
                'content' => Yii::t('app/notification', 'NEW_COMMENT_NOTIFICATION_CONTENT', Url::to($url, true)),
                ], [
                'permission' => 'projects',
                'unit'       => [$model->project->owner_id, $model->project->company_id],
            ]);

            return $this->redirect($url);
        } else {
            return $this->render('create', [
                    'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Comment model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param  integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['document/view', 'id' => $model->document_id, 'version' => $model->doc_version]);
        } else {
            return $this->render('update', [
                    'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Comment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param  integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Comment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param  integer               $id
     * @return Comment               the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comment::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionXml($id)
    {
        Yii::$app->response->format = Response::FORMAT_XML;

        return $this->findModel($id);
    }

    public function actionTask($id)
    {
        Yii::$app->response->format = Response::FORMAT_XML;

        Yii::$app->response->formatters[Response::FORMAT_XML]['rootTag'] = 'TaskList';

        return $this->findModel($id)->getCryptoTask();
    }

    public function actionSignature($id)
    {
        Yii::$app->response->format = Response::FORMAT_RAW;

        $comment = $this->findModel($id);

        $comment->signature = Yii::$app->request->post('signature');

        if (!$comment->signature) {
            Yii::$app->response->formatters[Response::FORMAT_XML]['rootTag'] = 'error';
            throw new BadRequestHttpException();
        }
        if (!$comment->save()) {
            Yii::$app->response->formatters[Response::FORMAT_XML]['rootTag'] = 'error';

            return $comment->errors;
        }

        return 'OK';
    }

}

yii-examples/controllers/DocumentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Comment;
use app\models\Document;
use app\models\DocumentSearch;
use app\models\Notification;
use lib\web\Controller;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * DocumentController implements the CRUD actions for Document model.
 */
class DocumentController extends Controller
{
    public $enableCsrfValidation = false;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => [
                            'signature', 'xml',
                        ],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['documents', 'document.upload'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => [
                            'approve-document'
                        ],
                        'roles'   => [
                            'document.approve'
                        ],
                    ],
                    [
                        'allow'   => true,
                        'actions' => [
                            'delete'
                        ],
                        'roles'   => [
                            'document.delete'
                        ],
                    ],
                ]
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionDownload($id, $version = null)
    {
        $doc = $this->findModel($id, $version);
        if (!$doc) {
            throw new NotFoundHttpException();
        }

        return Yii::$app->response->sendFile($doc->getFilePath(), $doc->name);
    }

    /**
     * Lists all Document models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel  = new DocumentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                'searchModel'  => $searchModel,
                'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Document model.
     * @param  integer $id
     * @return mixed
     */
    public function actionView($id, $version = null)
    {
        $doc = $this->findModel($id, $version);

        return $this->render('view', [
                'model'           => $doc,
                'documentModel'   => new Document([
                    'id'         => $doc->id,
                    'project_id' => $doc->project_id,
                    'title'      => $doc->title,
                    'version'    => $doc->version + 1,
                    ]),
                'commentList'     => new ActiveDataProvider([
                    'query'      => $doc->getComments(),
                    'pagination' => [
                        'pageSize' => 20,
                    ],
                    ]),
                'newComment'      => new Comment([
                    'document_id' => $doc->id,
                    'project_id'  => $doc->project_id,
                    'doc_version' => $doc->version,
                    ]),
                'previousVerions' => new ActiveDataProvider([
                    'query'      => Document::find()->orderBy('version DESC')->where(['id' => $id]),
                    'pagination' => [
                        'pageSize' => 20,
                    ],
                    ]),
        ]);
    }

    /**
     * Creates a new Document model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Document();

        if ($model->load(Yii::$app->request->post()) && $model->save() && $model->file->saveAs($model->getFilePath())) {
            $url          = [
                'project/view',
                'id'   => $model->project_id,
                'type' => $model->type,
            ];
            $notification = new Notification('notice');
            $notification->add(Notification::NOTIFICATION_EXTERNAL, [
                'title'   => Yii::t('app/notification', 'NEW_DOCUMENT_NOTIFICATION_TITLE'),
                'content' => Yii::t('app/notification', 'NEW_DOCUMENT_NOTIFICATION_CONTENT', Url::to($url, true)),
                ], [
                'permission' => 'projects',
                'unit'       => [$model->project->owner_id, $model->project->company_id],
            ]);

            return $this->redirect($url);
        } else {
            return $this->render('create', [
                    'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Document model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param  integer $id
     * @return mixed
     */
    public function actionUpdate($id, $version)
    {
        $model = $this->findModel($id, $version);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id, 'version' => $model->version]);
        } else {
            return $this->render('update', [
                    'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Document model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param  integer $id
     * @return mixed
     */
    public function actionDelete($id, $version)
    {
        $this->findModel($id, $version)->delete();

        return $this->redirect(['index']);
    }

    public function actionApproveDocument($id, $version)
    {
        $model = $this->findModel($id, $version);

        if ($model->isApprovedByType($model->type)) {
            Yii::$app->session->setFlash('danger', Yii::t('app/document', 'DOCUMENT_APPROVED'));

            return $this->redirect(['project/view', 'id' => $model->project_id, 'type' => $model->type]);
        }

        $url = ['project/view', 'id' => $model->project_id, 'type' => $model->type];
        if ($model->approve(Yii::$app->user->identity)) {
            $notification = new Notification('notice');
            $notification->add(Notification::NOTIFICATION_EXTERNAL, [
                'title'   => Yii::t('app/notification', 'DOCUMENT_APPROVED_NOTIFICATION_TITLE'),
                'content' => Yii::t('app/notification', 'DOCUMENT_APPROVED_NOTIFICATION_CONTENT', Url::to($url, true)),
                ], [
                'permission' => 'projects',
                'unit'       => [$model->project->owner_id, $model->project->company_id],
            ]);

            Yii::$app->session->setFlash('success', Yii::t('app/document', 'DOCUEMENT_HAS_BEEN_APPROVED'));
        } else {
            Yii::$app->session->setFlash('danger', Yii::t('app/document', 'DOCUMENT_CANNOT_BE_APPROVED'));
        }

        return $this->redirect($url);
    }

    /**
     * Finds the Document model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param  integer               $id
     * @return Document              the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $version = null)
    {
        if ($version === null) {
            $version = Document::find()->select([new Expression('MAX(version) AS mv')])->where(['id' => $id])->scalar();
        }
        if ($version !== false && ($model = Document::findOne(['id' => $id, 'version' => $version])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionXml($id)
    {
        Yii::$app->response->format = Response::FORMAT_XML;

        return $this->findModel($id);
    }

    public function actionTask($id)
    {
        Yii::$app->response->format = Response::FORMAT_XML;

        Yii::$app->response->formatters[Response::FORMAT_XML]['rootTag'] = 'TaskList';

        return $this->findModel($id)->getCryptoTask();
    }

    public function actionSignature($id)
    {
        Yii::$app->response->format = Response::FORMAT_XML;

        $model = $this->findModel($id);

        $model->signature = Yii::$app->request->post('signature');

        if (!$model->signature) {
            Yii::$app->response->formatters[Response::FORMAT_XML]['rootTag'] = 'error';
            throw new BadRequestHttpException();
        }

        $model->signature_type = Document::SIGNED_DIGITALLY;
        if (!$model->save()) {
            Yii::$app->response->formatters[Response::FORMAT_XML]['rootTag'] = 'error';

            return $model->errors;
        }

        Yii::$app->response->format = Response::FORMAT_RAW;

        return 'OK';
    }

}

yii-examples/views/document/_form.php
<?php
use app\models\Document;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Document */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="document-form">

    <?php
    $form = ActiveForm::begin([
            'action'  => [$model->isNewRecord ? 'document/create' : 'document/update', 'id' => $model->id, 'type' => $model->type, 'version' => $model->version],
            'options' => ['enctype' => 'multipart/form-data'],
    ]);
    ?>

    <?= Html::activeHiddenInput($model, 'project_id') ?>
    <?= $model->version ? Html::activeHiddenInput($model, 'version') : '' ?>
    <?= $model->id ? Html::activeHiddenInput($model, 'id') : '' ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => 256]) ?>

    <?= $model->isNewRecord ? $form->field($model, 'file')->fileInput(['class' => 'btn btn-warning']): Html::activeHiddenInput($model, 'file') ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>
    <?=
    $form->field($model, 'signature_type')->dropDownList([
        Document::NO_SIGNATURE     => Yii::t('app/document', 'UNSIGNED'),
        Document::SIGNED_BY_HAND   => Yii::t('app/document', 'SIGNED_BY_HAND'),
        Document::SIGNED_DIGITALLY => Yii::t('app/document', 'SIGNED_DIGITALLY'),
    ])
    ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'CREATE'), ['class' => 'btn btn-success']) ?>
        <?= Html::a(Yii::t('app', 'CANCEL'), ['project/view', 'id' => $model->project_id, 'type' => $model->type], ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii-examples/views/document/_search.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DocumentSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="document-search">

    <?php
    $form = ActiveForm::begin([
            'action' => ['index'],
            'method' => 'get',
    ]);
    ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?= $form->field($model, 'project_id') ?>

    <?php // echo $form->field($model, 'title')    ?>

    <?php // echo $form->field($model, 'size')     ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app/document', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app/document', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii-examples/views/document/create.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Document */

$this->title = Yii::t('app/document', 'CREATE_DOCUMENT', [
        'modelClass' => 'Document',
    ]);
?>
<div class="document-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>

yii-examples/views/document/index.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\DocumentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app/document', 'DOCUMENTS');
?>
<div class="document-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel'  => $searchModel,
        'columns'      => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'name',
            'created_at',
            'updated_at',
            'project_id',
            'title',
            'size',
            ['class'    => 'yii\grid\ActionColumn',
                'template' => '{view} {update}'],
        ],
    ]);
    ?>

</div>

yii-examples/views/document/update.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Document */

$this->title = Yii::t('app/document', 'UPDATE_DOCUMENT', [
        'modelClass' => 'Document',
    ]);
?>
<div class="document-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>

yii-examples/views/document/view.php
<?php
use app\assets\KirAsset;
use yii\bootstrap\Modal;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;

$kir = KirAsset::register($this);

/* @var $this yii\web\View */
/* @var $model app\models\Document */
?>
<div class="document-view">
    <h1><?= Html::encode($model->title . " (wersja {$model->version})") ?></h1>
    <p>
        <?= Html::a(Yii::t('app', 'BACK'), ['project/view', 'id' => $model->project_id, 'type' => $model->type], ['class' => 'btn btn-primary']) ?>
        <?php if ($model->canManageType($model->type)): ?>
            <?=
            DetailView::widget([
                'model'      => $model,
                'attributes' => [
                    'name',
                    'description:ntext',
                ],
            ])
            ?>
            <?php
            Modal::begin([
                'id'           => 'modal',
                'toggleButton' => [
                    'class' => 'btn btn-success modalButton',
                    'label' => Yii::t('app/document', 'UPLOAD_NEW_VERSION'),
                ],
            ]);
            ?>
        <div class='modalContent'>
            <?=
            $this->render('/document/_form', [
                'model' => $documentModel,
            ])
            ?>
        </div>
        <?php Modal::end(); ?>
    <?php endif; ?>
</p>


<div class="comment-index">
    <?= Html::tag('div', '', ['id' => 'appletContainer']); ?>
    <?php $this->registerJs('
    jQuery("#loadButton").click(function () {
        if (typeof signer !== "object") {
            jQuery("#appletContainer").load("' . Url::to(['applet'], true) . '",{},function () {
                jQuery("#loadButton").remove();
                signer.initialize();
            });
        }
    });'); ?>
    <h2><?= Html::encode(Yii::t('app/comment', "COMMENT_LIST")) ?></h2>
    <?=
    GridView::widget([
        'dataProvider' => $commentList,
        'columns'      => [
            'created_at:datetime',
            [
                'attribute' => 'author',
                'header'    => Yii::t('app/comment', "AUTHOR"),
                'format'    => 'html',
                'value'     => function ($model) {
                if ($model->author) {
                    return $model->author->name;
                }

                return '<s>' . $model->getArchiveAuthor()['name'] . '</s>';
            }
            ],
            'doc_version',
            [
                'attribute' => 'content',
                'format'    => 'ntext',
                'value'     => function ($model) {
                return $model->content
                    . ($model->info_attachment ? ' /zał.: ' . $model->info_attachment : '')
                    . ($model->info_page ? ' /str.: ' . $model->info_page : '')
                    . ($model->info_paragraph ? ' /par.: ' . $model->info_paragraph : '')
                ;
            }
            ],
            [
                'header' => Yii::t('app', "SIGNATURE") . '<br />' . Html::button(Yii::t('app', 'LOAD_APPLET'), ['class' => 'btn btn-primary', 'id' => 'loadButton']),
                'format' => 'raw',
                'value'  => function ($model) {
                if ($model->signature) {
                    return '<span class="glyphicon glyphicon-ok"></span>';
                } else {
                    return Html::a('<span class="glyphicon glyphicon-barcode"></span>', '#', [
                            'title' => Yii::t('app', 'SIGN'),
                            'class' => 'signButton',
                            'style' => 'display: none;',
                            'data'  => [
                                'task' => Url::to(['comment/task', 'id' => $model->id], true),
                            ],
                    ]);
                }
            }
            ],
        ],
    ]);
    ?>
</div>

<div class="comment-form">
    <h3><?= Html::encode(Yii::t('app/comment', "ADD_COMMENT")) ?></h3>
    <?php
    $form = ActiveForm::begin([
            'action' => ['comment/create'],
    ]);
    ?>

    <?= $form->field($newComment, 'content')->textarea(['rows' => 6]) ?>
    <?= $form->field($newComment, 'info_attachment')->textInput() ?>
    <?= $form->field($newComment, 'info_page')->textInput() ?>
    <?= $form->field($newComment, 'info_paragraph')->textInput() ?>

    <?= Html::activeHiddenInput($newComment, 'project_id') ?>
    <?= Html::activeHiddenInput($newComment, 'document_id') ?>
    <?= Html::activeHiddenInput($newComment, 'doc_version') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'CREATE'), ['class' => 'btn btn-success']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

<div class="document-index">
    <h1><?= Html::encode(Yii::t('app/document', 'ALL_VERSIONS')) ?></h1>
    <?=
    GridView::widget([
        'dataProvider' => $previousVerions,
        'columns'      => [
            'version',
            [
                'attribute' => 'title',
                'format'    => 'html',
                'value'     => function ($model) {
                return Html::a($model->title, Yii::$app->urlManager->createUrl(['document/download', 'id' => $model->id, 'version' => $model->version]));
            }
            ],
            'created_at',
        ],
    ]);
    ?>
</div>

</div>